apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-curator
  namespace: dev
  labels:
    k8s-app: elasticsearch-logging
spec:
  schedule: "0 0 * * 3,5,7"  # Run at midnight on Wednesday, Friday, and Sunday
  jobTemplate:
    spec:
      template:
        metadata:
          name: elasticsearch-curator
          labels:
            k8s-app: elasticsearch-logging
        spec:
          serviceAccountName: elasticsearch-curator-sa
          restartPolicy: "Never"
          containers:
          - name: curator
            image: bobrik/curator:5.8.4
            args:
              - /curator/curator
              - --host
              - elasticsearch-logging
              - delete_indices
              - --filter_list
              - '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":7},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]'
            env:
              - name: ELASTICSEARCH_HOST
                value: "elasticsearch-logging"
              - name: LOG_LEVEL
                value: "INFO"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "500m"
          backoffLimit: 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-curator-sa
  namespace: dev
