apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
spec:
  limits:
  - max:
      cpu: "8"
      memory: "30Gi"
    min:
      cpu: "100m"
      memory: "256Mi"
    type: Container
